version: '3.8'

services:
  php:
    container_name: php
    build:
      context: ./php
    volumes:
      - ./app:/var/www/app
    networks:
      app:
        ipv4_address: 10.5.0.10
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      app:
        ipv4_address: 10.5.0.11
  database:
    image: 'mariadb:10'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '${DB_HOST}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'data:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
    networks:
      app:
        ipv4_address: 10.5.0.12
volumes:
  data:
networks:
  app:
    ipam:
      config:
        - subnet: 10.5.0.0/16